services:
  db:
    image: pgvector/pgvector:pg16
    container_name: glyfs_db
    environment:
      - POSTGRES_DB=glyfs
      - POSTGRES_USER=glyfs
      - POSTGRES_PASSWORD=glyfs
    ports:
      - "5433:5432"
    volumes:
      - glyfs-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glyfs -d glyfs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  glyfs-db-data:
